### ISSUE TITLE
Questions about code

### ISSUE THREAD

**Issue by Xu-Qingchao** [mengmengliu1998/LAformer#3]
Hello, thank you very much for your excellent work！
In model_main.py
```
    def forward(self, mapping: List[Dict], device):
        vector_matrix = utils.get_from_mapping(mapping, 'matrix')
        for i in range(19):
            print(vector_matrix[i][0])
        # vectors of i_th element is matrix[polyline_spans[i]]
        polyline_spans = utils.get_from_mapping(mapping, 'polyline_spans')
        batch_size = len(vector_matrix)
        utils.batch_origin_init(mapping)
```
I want to print the vector of the first position of the intelligent agent. But I found that in some epoch, the x coordinate of the agent becomes negative. Such like this.
```
[ -0.07302541 -24.56219269  -0.07513113 -23.30788955   0.10382336
   0.           1.           0.           0.           1.
   0.           0.           0.           0.           0.
  -0.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
   0.           0.           0.           0.          -0.
   0.          -0.        ]
```
It should have been like this.
```
[  0.07302541 -24.56219269   0.07513113 -23.30788955   0.10382336
   0.           1.           0.           0.           1.
   0.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
   0.           0.        ]
```
I want to know if this is correct? What is the reason for this happening? thanks.

**Comment by Harry333777** [comment]
> Hello, thank you very much for your excellent work！ In model_main.py
> 
> ```
>     def forward(self, mapping: List[Dict], device):
>         vector_matrix = utils.get_from_mapping(mapping, 'matrix')
>         for i in range(19):
>             print(vector_matrix[i][0])
>         # vectors of i_th element is matrix[polyline_spans[i]]
>         polyline_spans = utils.get_from_mapping(mapping, 'polyline_spans')
>         batch_size = len(vector_matrix)
>         utils.batch_origin_init(mapping)
> ```
> 
> I want to print the vector of the first position of the intelligent agent. But I found that in some epoch, the x coordinate of the agent becomes negative. Such like this.
> 
> ```
> [ -0.07302541 -24.56219269  -0.07513113 -23.30788955   0.10382336
>    0.           1.           0.           0.           1.
>    0.           0.           0.           0.           0.
>   -0.           0.           0.           0.           0.
>    0.           0.           0.           0.           0.
>    0.           0.           0.           0.          -0.
>    0.          -0.        ]
> ```
> 
> It should have been like this.
> 
> ```
> [  0.07302541 -24.56219269   0.07513113 -23.30788955   0.10382336
>    0.           1.           0.           0.           1.
>    0.           0.           0.           0.           0.
>    0.           0.           0.           0.           0.
>    0.           0.           0.           0.           0.
>    0.           0.           0.           0.           0.
>    0.           0.        ]
> ```
> 
> I want to know if this is correct? What is the reason for this happening? thanks.
Hello, I have been working on a reproduction of this article recently. Can you leave a personal address on your homepage for me to contact you?

**Comment by Xu-Qingchao** [comment]
@Harry333777 You can find email on my homepage.

**Comment by mengmengliu1998** [comment]
Hi, I think this is the result of coordinate normalisation due to inaccurate yaw angles during data preprocessing. When you look at the argoverse trajectory data, you will see that in some cases the trajectory coordinates are very noisy.

**Comment by Xu-Qingchao** [comment]
thanks, When I print the yaw angles, each epoch is the same, but the x coordinate occasionally appears negative. I don't know where the code caused this coordinate normalization. Will this phenomenon affect the training results?

**Comment by mengmengliu1998** [comment]
This phenomenon affects network learning because the network receives noisy training data. However, other models on the argoverse benchmark are trained with the same data, so it is fair for comparison with other models. https://github.com/mengmengliu1998/LAformer/blob/main/src/datascripts/dataset_argoverse.py#L408

**Comment by Xu-Qingchao** [comment]
Okay, I understand. Thank you very much！
